// <auto-generated/>
// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.

using System.Xml;

namespace TcHaxx.ProtocGenTc.TcPlcObjects;

/// <remarks/>
[Serializable()]
[System.ComponentModel.DesignerCategory("code")]
[System.Xml.Serialization.XmlType(AnonymousType = true)]
[System.Xml.Serialization.XmlRoot(Namespace = "", IsNullable = false, ElementName = "TcPlcObject")]
public partial class TcDUT
{

    private TcPlcObjectDUT dUTField;

    private string versionField = Constants.TC_PLC_OBJECT_VERSION;

    /// <remarks/>
    public TcPlcObjectDUT DUT
    {
        get
        {
            return this.dUTField;
        }
        set
        {
            this.dUTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[Serializable()]
[System.ComponentModel.DesignerCategory("code")]
[System.Xml.Serialization.XmlType(AnonymousType = true)]
public partial class TcPlcObjectDUT
{

    private XmlCDataSection declarationField;

    private string nameField;

    private string idField;

    /// <remarks/>
    public XmlCDataSection Declaration
    {
        get
        {
            return this.declarationField;
        }
        set
        {
            this.declarationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute()]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

