// <auto-generated />

using System.Xml;

namespace TcHaxx.ProtocGenTc.TcPlcObjects;


// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "TcPlcObject")]
public partial class TcPOU
{

    private TcPlcObjectPOU pOUField;

    private string versionField = Constants.TcPlcObjectVersion;

    private string productVersionField = string.Empty;

    /// <remarks/>
    public TcPlcObjectPOU POU
    {
        get
        {
            return this.pOUField;
        }
        set
        {
            this.pOUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductVersion
    {
        get
        {
            return this.productVersionField;
        }
        set
        {
            this.productVersionField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TcPlcObjectPOU
{

    private XmlCDataSection declarationField;

    private TcPlcObjectPOUImplementation implementationField;

    private TcPlcObjectPOUMethod[] methodField;

    private string nameField;

    private string idField;

    private string specialFuncField = "None";

    /// <remarks/>
    public XmlCDataSection Declaration
    {
        get
        {
            return this.declarationField;
        }
        set
        {
            this.declarationField = value;
        }
    }

    /// <remarks/>
    public TcPlcObjectPOUImplementation Implementation
    {
        get
        {
            return this.implementationField;
        }
        set
        {
            this.implementationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Method")]
    public TcPlcObjectPOUMethod[] Method
    {
        get
        {
            return this.methodField;
        }
        set
        {
            this.methodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SpecialFunc
    {
        get
        {
            return this.specialFuncField;
        }
        set
        {
            this.specialFuncField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TcPlcObjectPOUImplementation
{

    private XmlCDataSection stField;

    /// <remarks/>
    public XmlCDataSection ST
    {
        get
        {
            return this.stField;
        }
        set
        {
            this.stField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TcPlcObjectPOUMethod
{

    private XmlCDataSection declarationField;

    private TcPlcObjectPOUMethodImplementation implementationField;

    private string nameField;

    private string idField;

    /// <remarks/>
    public XmlCDataSection Declaration
    {
        get
        {
            return this.declarationField;
        }
        set
        {
            this.declarationField = value;
        }
    }

    /// <remarks/>
    public TcPlcObjectPOUMethodImplementation Implementation
    {
        get
        {
            return this.implementationField;
        }
        set
        {
            this.implementationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TcPlcObjectPOUMethodImplementation
{

    private XmlCDataSection stField;

    /// <remarks/>
    public XmlCDataSection ST
    {
        get
        {
            return this.stField;
        }
        set
        {
            this.stField = value;
        }
    }
}


