// <auto-generated />
// generated with https://json2csharp.com/code-converters/xml-to-csharp
// but modified, e.g. object -> XmlCDataSection, string Declaration -> XmlCDataSection Declaration
using System.Xml;
using System.Xml.Serialization;

namespace TcHaxx.ProtocGenTc.TcPlcObjects;

[XmlRoot(ElementName = "Implementation")]
public class Implementation
{
    [XmlElement(ElementName = "ST")]
    public XmlCDataSection ST { get; set; }
}

[XmlRoot(ElementName = "Method")]
public class Method
{

    [XmlElement(ElementName = "Declaration")]
    public XmlCDataSection Declaration { get; set; }

    [XmlElement(ElementName = "Implementation")]
    public Implementation Implementation { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }

    [XmlAttribute(AttributeName = "Id")]
    public string Id { get; set; }

    [XmlText]
    public string Text { get; set; }
}

[XmlRoot(ElementName = "Get")]
public class Get
{

    [XmlElement(ElementName = "Declaration")]
    public XmlCDataSection Declaration { get; set; }

    [XmlElement(ElementName = "Implementation")]
    public Implementation Implementation { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }

    [XmlAttribute(AttributeName = "Id")]
    public string Id { get; set; }

    [XmlText]
    public string Text { get; set; }
}

[XmlRoot(ElementName = "Property")]
public class Property
{

    [XmlElement(ElementName = "Declaration")]
    public XmlCDataSection Declaration { get; set; }

    [XmlElement(ElementName = "Get")]
    public Get Get { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }

    [XmlAttribute(AttributeName = "Id")]
    public string Id { get; set; }

    [XmlText]
    public string Text { get; set; }

    [XmlElement(ElementName = "Set")]
    public Set Set { get; set; }
}

[XmlRoot(ElementName = "Set")]
public class Set
{

    [XmlElement(ElementName = "Declaration")]
    public XmlCDataSection Declaration { get; set; }

    [XmlElement(ElementName = "Implementation")]
    public Implementation Implementation { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }

    [XmlAttribute(AttributeName = "Id")]
    public string Id { get; set; }

    [XmlText]
    public string Text { get; set; }
}

[XmlRoot(ElementName = "POU")]
public class TcPOU
{

    [XmlElement(ElementName = "Declaration")]
    public XmlCDataSection Declaration { get; set; }

    [XmlElement(ElementName = "Implementation")]
    public Implementation Implementation { get; set; }

    [XmlElement(ElementName = "Method")]
    public List<Method> Method { get; set; }

    [XmlElement(ElementName = "Property")]
    public List<Property> Property { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }

    [XmlAttribute(AttributeName = "Id")]
    public string Id { get; set; }

    [XmlAttribute(AttributeName = "SpecialFunc")]
    public string SpecialFunc { get; set; }

    [XmlText]
    public string Text { get; set; }
}

[XmlRoot(ElementName = "TcPlcObject")]
public class TcPlcObject
{

    [XmlElement(ElementName = "POU")]
    public TcPOU POU { get; set; }

    [XmlAttribute(AttributeName = "Version")]
    public string Version { get; set; }

    [XmlText]
    public string Text { get; set; }
}

