name: CI/CD
on:
  push:
    branches:
        - main
    paths:
      - 'src/**'
      - 'tests/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'

  workflow_dispatch:

env:
  solution: ./protoc-gen-twincat.sln
  dotnet_versions: |
                    8.0.x
                    9.0.x
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  ci-protoc-gen-twincat:
    name: CI - protoc-gen-twincat
    runs-on: ubuntu-latest
    env:

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.dotnet_versions}}
      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }}
      - name: Build
        run: dotnet build -c Release --no-restore ${{ env.solution }}
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal ${{ env.solution }}
  
  cd-protoc-gen-twincat:
    needs:
      - ci-protoc-gen-twincat
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    name: CD - protoc-gen-twincat
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet_versions }}         
